name: "Wdrożenie Aplikacji (Lambda & Frontend)"

on:
  push:
    paths:
      - "app/**"
    branches:
      - main

jobs:
  deploy-backend:
    name: "Deploy Lambda"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      FUNCTION_NAME: ${{ vars.SUB_DOMAIN_API }}

    steps:
      - name: "Pobranie kodu"
        uses: actions/checkout@v4

      - name: "Pakowanie kodu Lambdy"
        run: |
          cd app/backend
          zip -r ../../lambda.zip .
          cd ../..

      - name: "Publikacja Artefaktu Backend"
        uses: actions/upload-artifact@v4
        with:
          name: backend-release-${{ github.run_number }}
          path: lambda.zip

      - name: "Aktualizacja kodu Lambdy w AWS"
        run: |
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://lambda.zip \
            --region "$AWS_REGION"

  deploy-frontend:
    name: "Deploy Frontend S3"
    runs-on: ubuntu-latest
    needs: deploy-backend
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      SUB_DOMAIN: ${{ vars.SUB_DOMAIN }}
      MAIN_DOMAIN: ${{ vars.MAIN_DOMAIN }}
      BUCKET_NAME: ${{ vars.SUB_DOMAIN }}.${{ vars.MAIN_DOMAIN }}

    steps:
      - name: "Pobranie kodu"
        uses: actions/checkout@v4

      - name: "Publikacja Artefaktu Frontend"
        uses: actions/upload-artifact@v4
        with:
          name: frontend-release-${{ github.run_number }}
          path: app/frontend/

      - name: "Wysyłka plików na S3"
        run: |
          aws s3 sync app/frontend/ s3://$BUCKET_NAME --delete --region "$AWS_REGION"

      - name: "Powiadomienie o sukcesie aplikacji"
        if: success()
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          SUB_DOMAIN: ${{ vars.SUB_DOMAIN }}
          MAIN_DOMAIN: ${{ vars.MAIN_DOMAIN }}
        run: |
          TOPIC_ARN=$(aws sns list-topics \
            --query "Topics[?contains(TopicArn, 'devops-alerts')].TopicArn" \
            --output text \
            --region "$AWS_REGION")

          aws sns publish \
            --topic-arn "$TOPIC_ARN" \
            --subject "Sukces: Aplikacja wdrożona" \
            --message "Wersja kodu (Lambda & Frontend) została pomyślnie wdrożona na środowisko $SUB_DOMAIN.$MAIN_DOMAIN." \
            --region "$AWS_REGION"
